# Tarea 1 - Machine learning

## Ejercicio 3 

Utilizando un cuaderno de Jupyter Notebook y el lenguaje de programación Python, realiza las siguientes operaciones: 

- Genera una matriz cuadrada de 4x4. 

- Calcula su inversa y su traspuesta. 

- Multiplica la matriz por un escalar. 

- Realiza el producto interno con una nueva matriz de dimensiones 4x2. 

In [62]:
import numpy as np
import random

In [19]:
#Se hace una matriz de 4x4 con valores aleatorios entre 0 y 100
matrix = np.random.randint(0, 10, size=(4, 4))
matrix

array([[3, 0, 2, 8],
       [0, 5, 6, 5],
       [6, 9, 8, 7],
       [2, 8, 0, 3]])

### Inversa de una matriz

Utilizando el método de adjunción, la solución es de la siguiente manera

1. $$A^-1 = \frac{(A^*)^T}{|A|}$$

Donde:
$$A-1$$ Matriz Inversa
$$|A|$$ Determinante de la matriz
$$A^*$$ Matriz adjunta
$$(A^*)^T$$ Matriz traspuesta de la adjunta

In [33]:
#Inversa de la matrix utilizando métodos matemáticos

# Determinante de la matriz
det_A = np.linalg.det(matrix)

#Matriz adjunta
def adjunta(matrix):
    # Obtener la matriz de cofactores
    cofactors = np.zeros(matrix.shape)
    rows, cols = matrix.shape
    
    for i in range(rows):
        for j in range(cols):
            # Obtener la submatriz al eliminar la fila i y columna j
            minor = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
            # Calcular el cofactor
            cofactors[i, j] = ((-1) ** (i + j)) * np.linalg.det(minor)
    
    # Transponer la matriz de cofactores para obtener la adjunta
    return cofactors.T

adjunta_mat = adjunta(matrix)

#Matriz traspuesta de la adjunta
mat_tras_adj = adjunta_mat.T

inv_matrix = mat_tras_adj/det_A

print(inv_matrix)

#inversa de la matrix usando numpy
np.linalg.inv(matrix)

[[ 0.01369863 -0.05479452 -0.06849315  0.1369863 ]
 [-0.23919916  0.0337197   0.08061117  0.06954689]
 [ 0.17597471 -0.01159115  0.08166491 -0.08640674]
 [-0.04847208  0.11696523 -0.14225501  0.05374078]]


array([[ 0.01369863, -0.23919916,  0.17597471, -0.04847208],
       [-0.05479452,  0.0337197 , -0.01159115,  0.11696523],
       [-0.06849315,  0.08061117,  0.08166491, -0.14225501],
       [ 0.1369863 ,  0.06954689, -0.08640674,  0.05374078]])

## Transpuesta de una matriz
Se define una transpuesta matriz $$A^T$$ de tamaño nxn como:
$$A^t = \begin{bmatrix}
a_{1,1}      ... &a_{nx1}  \\
  ...      
 ...  ...&  \\a_{1xn}   
 ...& a_{nxn} & 
\end{bmatrix}$$

In [49]:
#Traspuesta de la matriz
print('Matriz inicial\n',matrix)
print('\nMatriz usando .T\n', matrix.T)

Matriz inicial
 [[3 0 2 8]
 [0 5 6 5]
 [6 9 8 7]
 [2 8 0 3]]

Matriz usando .T
 [[3 0 6 2]
 [0 5 9 8]
 [2 6 8 0]
 [8 5 7 3]]


In [47]:
#Sin usar .T
filas, columnas = matrix.shape
#Una matriz de 0 del mismo tamaño
tras = np.zeros((columnas, filas))

for i in range(filas):
    for j in range(columnas):
        tras[j,i] = matrix[i,j]
print('Matriz sin usar .T\n',tras)

Matriz sin usar .T
 [[3. 0. 6. 2.]
 [0. 5. 9. 8.]
 [2. 6. 8. 0.]
 [8. 5. 7. 3.]]


### Multiplicación por un escalar

Al multiplicarse por un escalar, no cambia la estructura y solo se multiplica por cada valor de la matriz

In [84]:
escalar = random.randint(0,100)
mult_escalar = escalar * matrix
print('Matriz inicial\n',matrix)

print(f'Matriz tras multiplicación por escalar {escalar}\n',mult_escalar)

Matriz inicial
 [[3 0 2 8]
 [0 5 6 5]
 [6 9 8 7]
 [2 8 0 3]]
Matriz tras multiplicación por escalar 3
 [[ 9  0  6 24]
 [ 0 15 18 15]
 [18 27 24 21]
 [ 6 24  0  9]]


### Multiplicación por una matrix 4x2

La multiplicación de una matriz $$A_{nxn}$$ se puede realizar con otra matriz $$B_{nxp}$$ siempre y cuando las entradas de las columnas de $$A$$ sean iguales a las filas de $$B$$. De tal manera que se obtiene lo siguiente $$A_{nxn} * B_{nxp} = C_{nxp}$$ 

In [122]:
#Sin utilizar numpy
matrix_2 = np.random.randint(0, 10, size=(4, 2))

row_1, col_1 = matrix.shape
row_2, col_2 = matrix_2.shape

C = np.zeros((row_1,col_2))

for i in range(row_1):
    for j in range(col_2):
        for k in range(row_2):
            C[i,j] += matrix[i,k] * matrix_2[k,j]

In [126]:
print('Matriz 1:\n',matrix)
print('Matriz 2:\n',matrix_2)
print('Resultado sin usar funciones:\n',C)
print('Resultado simplificado:\n',matrix.dot(matrix_2))

Matriz 1:
 [[3 0 2 8]
 [0 5 6 5]
 [6 9 8 7]
 [2 8 0 3]]
Matriz 2:
 [[3 9]
 [5 6]
 [1 1]
 [9 3]]
Resultado sin usar funciones:
 [[ 83.  53.]
 [ 76.  51.]
 [134. 137.]
 [ 73.  75.]]
Resultado simplificado:
 [[ 83  53]
 [ 76  51]
 [134 137]
 [ 73  75]]


## Ejercicio 4: 
Resuelve los siguientes sistemas de ecuaciones:

A. 

- x + 2y + 5z - 4w = 21
- 5x + 8y + z + w = -8
- 5x + 7y - 3y + 2w = 14
- -x + 3y + 9z - w = 5

B.

- 6x + 8z = 9
- 2x + 2y + z = 15
- 4x + y = -4

Al tener un sistema de ecuaciones con 4 fórmulas y 4 variables, la solución es sencilla. Utilizando el sistema de eliminación de Gauss, el cual, en resumidas cuentas, hace lo siguiente:


In [64]:
args = np.array([[1,2,5,-4],[5,8,1,1],[5,7,-3,2],[-1,3,9,-1]], dtype=float)
sol = np.array([21, 8, 14, 5], dtype=float)

matrix = np.hstack((args,sol.reshape(-1,1)))

In [66]:
#Sin utilizar alguna función:
def solucion_3var(matrix):
    fila, col = matrix.shape
    for i in range(fila):
        matrix[i] = matrix[i]/matrix[i,i]
        for j in range(i+1, fila):
            matrix[j] = matrix[j] - matrix[j,i] * matrix[i]
    x = np.zeros(fila)
    for i in range(fila-1, -1, -1):
        x[i] = matrix[i,-1] - np.dot(matrix[i,:-1],x)
    return x

In [68]:
solution = solucion_3var(matrix)

In [70]:
print('Solucion sin utilizar funciones de python\n', solution)
print('Solucion utilizando funciones de python\n', np.linalg.solve(args,sol))

Solucion sin utilizar funciones de python
 [-22.19298246  17.73684211  -9.33333333 -13.59649123]
Solucion utilizando funciones de python
 [-22.19298246  17.73684211  -9.33333333 -13.59649123]


In [72]:
# Ejercicio 2
args = np.array([[6,8,0],[2,2,1],[4,1,0]], dtype=float)
sol = np.array([9,15,-4], dtype=float)

matrix = np.hstack((args,sol.reshape(-1,1)))

In [74]:
solution = solucion_3var(matrix)

In [76]:
print('Solucion sin utilizar funciones de python\n', solution)
print('Solucion utilizando funciones de python\n', np.linalg.solve(args,sol))

Solucion sin utilizar funciones de python
 [-1.57692308  2.30769231 13.53846154]
Solucion utilizando funciones de python
 [-1.57692308  2.30769231 13.53846154]
